version: '3.8'

services:
  mariadb:
    container_name: mariadb
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    env_file:
      - .env
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ${DB_VOLUME:-database}:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  database: {
    driver: local
  }